### ISSUE TITLE
Backup Destination Settings

### ISSUE THREAD

**Issue by paulpinter** [kenstuddy/SaveBackup#1]
Hi Ken,

I'm a big fan of your plugin. I think it would be even better if the user could change the default backup repository.

Greetings to Canada,

 Paul

**Comment by kenstuddy** [comment]
Hi,

I am glad to hear you are a fan of my plugin, I always enjoy providing value to others. I'm not currently looking to enable changing the default backup location - my plugin is similar to other saving plugins for other IDEs and editors in that it uses a folder in the home directory, and it uses this location because doing so can avoid write permission errors on Windows and on Linux, plus then you only have one possible folder location to remember, etc. It keeps things simpler this way.

You are of course totally free to fork this repository and add in that functionality yourself if that is something that is really important to you, that is definitely fine by me.

Thanks,
Ken.
